#!/usr/bin/env bash
#
#    Copyright 2010-2026 the original author or authors.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# ============================================================================
# HSQLDB Full Database Export for Migration — Read-Only, Non-Destructive
# ============================================================================
#
# Exports all 13 HSQLDB tables from the JPetStore monolith database to individual
# CSV files without modifying the source database. Invokes the migration module's
# DataExporter Java class via JDBC for read-only, RFC 4180-compliant CSV output.
# Produces a baseline row-count manifest used by downstream migration scripts
# (load-data.sh, validate-integrity.sh).
#
# Usage:
#   ./export-hsqldb.sh
#
# Environment Variables (all optional — sensible defaults provided):
#   HSQLDB_URL       JDBC URL       (default: jdbc:hsqldb:hsql://localhost:9001/jpetstore)
#   HSQLDB_USER      Database user  (default: sa)
#   HSQLDB_PASSWORD  Database pass  (default: empty)
#   EXPORT_DIR       Output dir     (default: <project_root>/migration/output/export)
#   JAVA_HOME        JDK location   (optional if java is already on PATH)
#
# Output Files:
#   <EXPORT_DIR>/<table>.csv               One CSV per table (13 files, header + data)
#   <EXPORT_DIR>/row-counts-baseline.txt   Baseline row counts for all 13 tables
#   <EXPORT_DIR>/export-manifest.properties  Export metadata (generated by DataExporter)
#
# Exit Codes:
#   0 — All 13 tables exported and verified successfully
#   1 — One or more failures occurred
# ============================================================================

set -euo pipefail

# ============================================================================
# Banner
# ============================================================================

echo "============================================"
echo "  JPetStore Migration — HSQLDB Export"
echo "============================================"
echo ""
echo "HSQLDB full database export for migration"
echo "Read-only, non-destructive, idempotent"
echo ""

# ============================================================================
# Script Directory Resolution (works when run from any working directory)
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# ============================================================================
# Environment Variables and Defaults
# ============================================================================

HSQLDB_URL="${HSQLDB_URL:-jdbc:hsqldb:hsql://localhost:9001/jpetstore}"
HSQLDB_USER="${HSQLDB_USER:-sa}"
HSQLDB_PASSWORD="${HSQLDB_PASSWORD:-}"
EXPORT_DIR="${EXPORT_DIR:-${PROJECT_ROOT}/migration/output/export}"

# Java command — respects JAVA_HOME when set, otherwise relies on PATH
JAVA_CMD="${JAVA_HOME:+${JAVA_HOME}/bin/}java"
JAVAC_CMD="${JAVA_HOME:+${JAVA_HOME}/bin/}javac"

echo "Configuration:"
echo "  HSQLDB URL:      ${HSQLDB_URL}"
echo "  HSQLDB User:     ${HSQLDB_USER}"
echo "  Export Dir:      ${EXPORT_DIR}"
echo "  Project Root:    ${PROJECT_ROOT}"
echo ""

# ============================================================================
# Logging Helpers
# ============================================================================

log_info() {
    echo "[INFO]  $(date '+%Y-%m-%d %H:%M:%S') $*"
}

log_warn() {
    echo "[WARN]  $(date '+%Y-%m-%d %H:%M:%S') $*" >&2
}

log_error() {
    echo "[ERROR] $(date '+%Y-%m-%d %H:%M:%S') $*" >&2
}

# ============================================================================
# Table Definitions — All 13 HSQLDB Tables Organised by Bounded Context
# ============================================================================
# These MUST match exactly the 13 tables defined in jpetstore-hsqldb-schema.sql.
# The export order mirrors SchemaMapper.getAllTableNames():
#   Account DB → Catalog DB → Order DB, parents before children within each DB.

# Account bounded context (4 tables)
ACCOUNT_TABLES="signon account profile bannerdata"

# Catalog bounded context (5 tables)
CATALOG_TABLES="supplier category product item inventory"

# Order bounded context (4 tables)
ORDER_TABLES="sequence orders orderstatus lineitem"

# Combined list — all 13 tables in export order
ALL_TABLES="${ACCOUNT_TABLES} ${CATALOG_TABLES} ${ORDER_TABLES}"

# Tables that may legitimately have zero data rows in seed data
POSSIBLY_EMPTY_TABLES="orders orderstatus lineitem"

# ============================================================================
# Pre-flight Check 1: Java Runtime
# ============================================================================

log_info "Checking Java runtime..."
if ! command -v "${JAVA_CMD}" &>/dev/null; then
    log_error "Java not found. Set JAVA_HOME or ensure 'java' is on PATH."
    exit 1
fi
JAVA_VERSION=$("${JAVA_CMD}" -version 2>&1 | head -1)
log_info "Java: ${JAVA_VERSION}"

# ============================================================================
# Pre-flight Check 2: Migration JAR
# ============================================================================

log_info "Checking migration JAR..."
MIGRATION_JAR=""
for jar in "${PROJECT_ROOT}"/migration/target/migration-*.jar; do
    # Skip sources and javadoc JARs produced by Maven plugins
    case "${jar}" in
        *-sources.jar|*-javadoc.jar) continue ;;
    esac
    if [[ -f "${jar}" ]]; then
        MIGRATION_JAR="${jar}"
        break
    fi
done

if [[ -z "${MIGRATION_JAR}" ]]; then
    log_error "Migration JAR not found at migration/target/migration-*.jar"
    log_error "Build the migration module first:"
    log_error "  cd ${PROJECT_ROOT} && ./mvnw package -pl migration -DskipTests"
    exit 1
fi
log_info "Migration JAR: ${MIGRATION_JAR}"

# ============================================================================
# Pre-flight Check 3: Dependency JARs (HSQLDB driver, SLF4J, etc.)
# ============================================================================

DEP_DIR="${PROJECT_ROOT}/migration/target/dependency"
log_info "Checking dependency JARs..."

if [[ ! -d "${DEP_DIR}" ]] || [[ -z "$(ls "${DEP_DIR}"/*.jar 2>/dev/null || true)" ]]; then
    log_info "Dependency JARs not found. Copying via Maven dependency:copy-dependencies..."
    if ! (cd "${PROJECT_ROOT}" && ./mvnw dependency:copy-dependencies -B -q -pl migration 2>&1); then
        log_error "Failed to copy migration dependencies. Ensure Maven is configured correctly."
        exit 1
    fi
fi

# Verify the HSQLDB driver is present on the classpath
if ! ls "${DEP_DIR}"/hsqldb-*.jar 1>/dev/null 2>&1; then
    log_error "HSQLDB driver JAR not found in ${DEP_DIR}."
    log_error "Dependencies may not have been copied correctly."
    exit 1
fi
log_info "Dependency directory: ${DEP_DIR}"

# Build the classpath for Java invocation: migration JAR + all dependency JARs
CLASSPATH="${MIGRATION_JAR}:${DEP_DIR}/*"

# ============================================================================
# Pre-flight Check 4: HSQLDB Mode Detection and Connectivity Warning
# ============================================================================

if [[ "${HSQLDB_URL}" == *"hsql://"* ]]; then
    log_info "HSQLDB mode: Server (network connection to HSQLDB server process)"
elif [[ "${HSQLDB_URL}" == *"file:"* ]]; then
    log_info "HSQLDB mode: File-based (local database file)"
    log_warn "Ensure the HSQLDB database file is not locked by another process."
elif [[ "${HSQLDB_URL}" == *"mem:"* ]]; then
    log_info "HSQLDB mode: In-memory"
    log_warn "In-memory databases are volatile — ensure the database is populated before export."
elif [[ "${HSQLDB_URL}" == *"res:"* ]]; then
    log_info "HSQLDB mode: Resource-based (classpath resource)"
else
    log_warn "Unrecognised HSQLDB URL format: ${HSQLDB_URL}"
fi

# ============================================================================
# Pre-flight Check 5: HSQLDB Connectivity Test
# ============================================================================

log_info "Testing HSQLDB connectivity..."
CONN_TEST_DIR="$(mktemp -d)"

cat > "${CONN_TEST_DIR}/HsqldbConnTest.java" << 'JAVAEOF'
import java.sql.Connection;
import java.sql.DriverManager;
public class HsqldbConnTest {
    public static void main(String[] args) {
        try {
            String url  = args.length > 0 ? args[0] : "";
            String user = args.length > 1 ? args[1] : "";
            String pass = args.length > 2 ? args[2] : "";
            Connection conn = DriverManager.getConnection(url, user, pass);
            conn.setReadOnly(true);
            conn.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
            System.exit(1);
        }
    }
}
JAVAEOF

if "${JAVAC_CMD}" "${CONN_TEST_DIR}/HsqldbConnTest.java" -d "${CONN_TEST_DIR}" 2>/dev/null; then
    if timeout 15 "${JAVA_CMD}" -cp "${CONN_TEST_DIR}:${CLASSPATH}" HsqldbConnTest \
            "${HSQLDB_URL}" "${HSQLDB_USER}" "${HSQLDB_PASSWORD}" 2>/dev/null; then
        log_info "HSQLDB connectivity: OK"
    else
        log_warn "Could not connect to HSQLDB at ${HSQLDB_URL}"
        log_warn "The export will be attempted, but may fail if the database is unreachable."
    fi
else
    log_warn "Could not compile connectivity test. Skipping pre-flight connectivity check."
fi
rm -rf "${CONN_TEST_DIR}" 2>/dev/null || true

# ============================================================================
# Create Export Output Directory
# ============================================================================

mkdir -p "${EXPORT_DIR}"
log_info "Export output directory: ${EXPORT_DIR}"
echo ""

# ============================================================================
# Execute HSQLDB Export via DataExporter
# ============================================================================

echo "============================================"
echo "  Starting HSQLDB Export"
echo "============================================"
echo ""

TABLE_COUNT=0
for _ in ${ALL_TABLES}; do
    TABLE_COUNT=$((TABLE_COUNT + 1))
done

log_info "Invoking com.jpetstore.migration.DataExporter..."
log_info "Exporting ${TABLE_COUNT} tables: ${ALL_TABLES}"
echo ""

# DataExporter reads configuration from JVM system properties (-D flags).
# It iterates all 13 tables internally via SchemaMapper.getAllTableNames().
# Produces one <table>.csv per table plus export-manifest.properties.
# Exits with 0 on full success, 1 on any failure.
EXPORT_EXIT_CODE=0
"${JAVA_CMD}" \
    -Dhsqldb.url="${HSQLDB_URL}" \
    -Dhsqldb.user="${HSQLDB_USER}" \
    -Dhsqldb.password="${HSQLDB_PASSWORD}" \
    -Dexport.dir="${EXPORT_DIR}" \
    -cp "${CLASSPATH}" \
    com.jpetstore.migration.DataExporter || EXPORT_EXIT_CODE=$?

echo ""

if [[ ${EXPORT_EXIT_CODE} -ne 0 ]]; then
    log_error "DataExporter exited with code ${EXPORT_EXIT_CODE}."
    log_error "Review the output above for details on which tables failed."
    exit 1
fi

log_info "DataExporter completed successfully."
echo ""

# ============================================================================
# Row Count Verification and Baseline Recording
# ============================================================================

echo "============================================"
echo "  Verifying Export & Recording Baseline"
echo "============================================"
echo ""

EXPORT_TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S')"
BASELINE_FILE="${EXPORT_DIR}/row-counts-baseline.txt"
TOTAL_ROWS=0
VERIFICATION_FAILURES=0

# Associative array to store per-table row counts for summary generation
declare -A ROW_COUNTS

# Write the baseline manifest header
{
    echo "# HSQLDB Export Baseline Row Counts"
    echo "# Exported at: ${EXPORT_TIMESTAMP}"
    echo "# Source: ${HSQLDB_URL}"
    echo "# Export directory: ${EXPORT_DIR}"
    echo "#"
} > "${BASELINE_FILE}"

# Formatted verification table header
printf "  %-15s %10s %10s\n" "TABLE" "ROWS" "STATUS"
printf "  %-15s %10s %10s\n" "---------------" "----------" "----------"

for table in ${ALL_TABLES}; do
    csv_file="${EXPORT_DIR}/${table}.csv"

    # Check that the CSV file was produced
    if [[ ! -f "${csv_file}" ]]; then
        log_error "CSV file missing: ${csv_file}"
        printf "  %-15s %10s %10s\n" "${table}" "N/A" "MISSING"
        VERIFICATION_FAILURES=$((VERIFICATION_FAILURES + 1))
        ROW_COUNTS["${table}"]=0
        echo "${table}: MISSING" >> "${BASELINE_FILE}"
        continue
    fi

    # Count total lines (wc -l counts newline-terminated lines)
    total_lines=$(wc -l < "${csv_file}")

    # Data rows = total lines minus 1 header line
    if [[ ${total_lines} -gt 0 ]]; then
        data_rows=$((total_lines - 1))
    else
        data_rows=0
    fi

    ROW_COUNTS["${table}"]=${data_rows}
    TOTAL_ROWS=$((TOTAL_ROWS + data_rows))

    # Determine status — warn if a table that should have data is empty
    status="OK"
    if [[ ${data_rows} -eq 0 ]]; then
        is_possibly_empty=false
        for empty_candidate in ${POSSIBLY_EMPTY_TABLES}; do
            if [[ "${table}" == "${empty_candidate}" ]]; then
                is_possibly_empty=true
                break
            fi
        done
        if [[ "${is_possibly_empty}" == "false" ]]; then
            status="WARN:EMPTY"
            log_warn "Table ${table} exported 0 data rows but is expected to contain seed data."
        fi
    fi

    printf "  %-15s %10d %10s\n" "${table}" "${data_rows}" "${status}"
    echo "${table}: ${data_rows}" >> "${BASELINE_FILE}"
done

# Write baseline footer with totals
{
    echo "#"
    echo "# Total rows: ${TOTAL_ROWS}"
    echo "# Total tables: ${TABLE_COUNT}"
} >> "${BASELINE_FILE}"

echo ""
log_info "Baseline row counts written to: ${BASELINE_FILE}"
echo ""

# ============================================================================
# Export Integrity Checks
# ============================================================================

echo "============================================"
echo "  Export Integrity Checks"
echo "============================================"
echo ""

INTEGRITY_FAILURES=0

# --- Check 1: All 13 CSV files exist ---
log_info "Check 1/4: Verifying all ${TABLE_COUNT} CSV files exist..."
FOUND_COUNT=0
for table in ${ALL_TABLES}; do
    csv_file="${EXPORT_DIR}/${table}.csv"
    if [[ -f "${csv_file}" ]]; then
        FOUND_COUNT=$((FOUND_COUNT + 1))
    else
        log_error "  Missing: ${csv_file}"
        INTEGRITY_FAILURES=$((INTEGRITY_FAILURES + 1))
    fi
done
if [[ ${FOUND_COUNT} -eq ${TABLE_COUNT} ]]; then
    log_info "  PASS: All ${TABLE_COUNT} CSV files present."
else
    log_error "  FAIL: Only ${FOUND_COUNT}/${TABLE_COUNT} CSV files found."
fi

# --- Check 2: Every CSV file has at least a header row ---
log_info "Check 2/4: Verifying CSV files contain headers..."
HEADER_PASS=true
for table in ${ALL_TABLES}; do
    csv_file="${EXPORT_DIR}/${table}.csv"
    if [[ -f "${csv_file}" ]]; then
        line_count=$(wc -l < "${csv_file}")
        if [[ ${line_count} -lt 1 ]]; then
            log_error "  ${table}.csv is completely empty (no header row)."
            INTEGRITY_FAILURES=$((INTEGRITY_FAILURES + 1))
            HEADER_PASS=false
        fi
    fi
done
if [[ "${HEADER_PASS}" == "true" ]]; then
    log_info "  PASS: All CSV files contain header rows."
fi

# --- Check 3: Non-empty tables contain data rows ---
log_info "Check 3/4: Verifying expected non-empty tables have data..."
DATA_PASS=true
for table in ${ALL_TABLES}; do
    data_rows=${ROW_COUNTS["${table}"]:-0}
    is_possibly_empty=false
    for empty_candidate in ${POSSIBLY_EMPTY_TABLES}; do
        if [[ "${table}" == "${empty_candidate}" ]]; then
            is_possibly_empty=true
            break
        fi
    done
    if [[ ${data_rows} -eq 0 ]] && [[ "${is_possibly_empty}" == "false" ]]; then
        log_warn "  ${table}: 0 rows (expected non-empty in seed data)"
        DATA_PASS=false
    fi
done
if [[ "${DATA_PASS}" == "true" ]]; then
    log_info "  PASS: All expected non-empty tables contain data."
else
    log_info "  Check complete (warnings noted above — review if unexpected)."
fi

# --- Check 4: export-manifest.properties exists ---
log_info "Check 4/4: Verifying export manifest..."
if [[ -f "${EXPORT_DIR}/export-manifest.properties" ]]; then
    log_info "  PASS: export-manifest.properties exists."
else
    log_warn "  export-manifest.properties not found."
fi

echo ""

# ============================================================================
# Final Summary
# ============================================================================

# Build human-readable per-context summaries
build_context_summary() {
    local tables="$1"
    local result=""
    for tbl in ${tables}; do
        local count=${ROW_COUNTS["${tbl}"]:-0}
        if [[ -n "${result}" ]]; then
            result="${result}, "
        fi
        result="${result}${tbl}(${count})"
    done
    echo "${result}"
}

account_summary=$(build_context_summary "${ACCOUNT_TABLES}")
catalog_summary=$(build_context_summary "${CATALOG_TABLES}")
order_summary=$(build_context_summary "${ORDER_TABLES}")

echo "============================================"
echo "  HSQLDB EXPORT COMPLETE"
echo "============================================"
echo ""
echo "  Total tables exported: ${TABLE_COUNT}"
echo "  Export directory:      ${EXPORT_DIR}"
echo "  Baseline row counts:   ${BASELINE_FILE}"
echo ""
echo "  Account context: ${account_summary}"
echo "  Catalog context: ${catalog_summary}"
echo "  Order context:   ${order_summary}"
echo ""
echo "  Total rows exported: ${TOTAL_ROWS}"
echo ""
if [[ ${VERIFICATION_FAILURES} -gt 0 ]] || [[ ${INTEGRITY_FAILURES} -gt 0 ]]; then
    echo "  WARNING: ${VERIFICATION_FAILURES} verification failure(s), ${INTEGRITY_FAILURES} integrity failure(s)"
    echo ""
fi
echo "============================================"
echo ""

# Next-step instructions for the migration pipeline
echo "Next steps:"
echo "  1. Run provision-postgres.sh to create target PostgreSQL databases"
echo "  2. Run load-data.sh to load exported data into PostgreSQL"
echo "  3. Run validate-integrity.sh to verify data integrity"
echo ""

# ============================================================================
# Exit
# ============================================================================

if [[ ${VERIFICATION_FAILURES} -gt 0 ]] || [[ ${INTEGRITY_FAILURES} -gt 0 ]]; then
    log_error "Export completed with failures. Review warnings and errors above."
    exit 1
fi

log_info "Export completed successfully. All ${TABLE_COUNT} tables exported and verified."
exit 0
