/*
 *    Copyright 2010-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package com.jpetstore.order.repository;

import java.util.List;

import com.jpetstore.order.entity.Order;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for the {@link Order} entity (aggregate root) mapped
 * to the {@code orders} table in the Order Service's PostgreSQL database
 * ({@code jpetstore_order}).
 *
 * <p>This repository replaces the monolith's {@code org.mybatis.jpetstore.mapper.OrderMapper}
 * interface, which provided 4 methods:</p>
 * <ul>
 *   <li>{@code getOrdersByUsername(String)} → replaced by
 *       {@link #findByUsernameOrderByOrderDateDesc(String)}</li>
 *   <li>{@code getOrder(int)} → replaced by inherited {@link #findById(Integer)}</li>
 *   <li>{@code insertOrder(Order)} → replaced by inherited {@link #save(Object)}</li>
 *   <li>{@code insertOrderStatus(Order)} → NOT in this repository; handled by
 *       {@code OrderStatusRepository}</li>
 * </ul>
 *
 * <h3>Monolith SQL Pattern Changes</h3>
 * <p>The monolith's {@code OrderMapper.xml} JOINs {@code ORDERS} with {@code ORDERSTATUS}
 * to fetch the status column in both {@code getOrder} and {@code getOrdersByUsername} queries.
 * In the microservice architecture, the Order entity has its own {@code status} column
 * (for Saga state: PENDING/CONFIRMED/FAILED), eliminating the need for this JOIN.
 * OrderStatus records can be fetched separately via {@code OrderStatusRepository}.</p>
 *
 * <h3>Inherited CRUD Operations from JpaRepository</h3>
 * <ul>
 *   <li>{@code save(Order)} — persists or updates an Order entity. The {@code orderId}
 *       is auto-generated by the PostgreSQL {@code order_id_seq} sequence via
 *       {@code @SequenceGenerator} on the entity. With {@code CascadeType.ALL} on the
 *       {@code lineItems} collection, saving an Order also cascades to associated
 *       {@code LineItem} entities.</li>
 *   <li>{@code findById(Integer)} — retrieves an order by its primary key. Line items
 *       are LAZY-loaded and fetched on access.</li>
 *   <li>{@code findAll()} — retrieves all orders in the database.</li>
 *   <li>{@code deleteById(Integer)} — deletes an order by its primary key.</li>
 *   <li>{@code count()} — returns the total number of orders.</li>
 * </ul>
 *
 * <h3>Cross-Service Boundary Enforcement</h3>
 * <p>Per AAP §0.8.1, the cross-service FK {@code orders.userid → account.userid} has
 * been removed as a database constraint. The {@code username} field (mapped to the
 * {@code userid} column) is a plain String — user existence is verified at the
 * application layer via REST API call to Account Service. This repository does NOT
 * contain any JOIN or relationship-based queries involving accounts.</p>
 *
 * <h3>Thread-Safe ID Generation</h3>
 * <p>The monolith's non-thread-safe {@code getNextId("ordernum")} pattern (read-then-update
 * on the {@code sequence} table) is replaced by PostgreSQL's native {@code order_id_seq}
 * sequence at the entity level. This repository simply calls {@code save()} and the
 * database guarantees atomic, thread-safe ID generation (AAP §0.7.3).</p>
 *
 * @author Blitzy Platform
 * @see Order
 * @see org.springframework.data.jpa.repository.JpaRepository
 */
@Repository
public interface OrderRepository extends JpaRepository<Order, Integer> {

    /**
     * Finds all orders placed by a specific user, sorted by order date in
     * descending order (most recent orders first).
     *
     * <p>This derived query method replaces the monolith's
     * {@code OrderMapper.getOrdersByUsername(String username)} method. The monolith
     * SQL ({@code OrderMapper.xml}, lines 59-91) performs:</p>
     * <pre>
     * SELECT ... FROM ORDERS, ORDERSTATUS
     * WHERE ORDERS.USERID = #{value}
     *   AND ORDERS.ORDERID = ORDERSTATUS.ORDERID
     * ORDER BY ORDERDATE
     * </pre>
     *
     * <p>In the microservice, the JOIN with ORDERSTATUS is no longer needed because
     * the Order entity has its own {@code status} column for Saga state. Spring Data
     * JPA derives the following query from the method name:</p>
     * <pre>
     * SELECT * FROM orders WHERE userid = ? ORDER BY order_date DESC
     * </pre>
     *
     * <p>The {@code username} parameter maps to the Order entity's {@code username}
     * field, which is mapped to the {@code userid} column via
     * {@code @Column(name = "userid")} on the entity.</p>
     *
     * @param username the username (account userid) to search for; must not be
     *                 {@code null} or empty
     * @return a list of orders placed by the specified user, sorted by order date
     *         descending (most recent first); returns an empty list if no orders
     *         are found for the username
     */
    List<Order> findByUsernameOrderByOrderDateDesc(String username);

}
