/*
 *    Copyright 2010-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package com.jpetstore.order.repository;

import com.jpetstore.order.entity.LineItem;
import com.jpetstore.order.entity.Order;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.TestPropertySource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for {@link OrderRepository} using Spring Boot's
 * {@code @DataJpaTest} test slice.
 *
 * <p>This test class validates that the {@link Order} JPA entity is correctly
 * mapped to the {@code orders} PostgreSQL table with snake_case column names,
 * that PostgreSQL sequence-based ID generation works, and that all query methods
 * produce results identical to the monolith's {@code OrderMapper}.</p>
 *
 * <p>Test patterns are derived from the monolith's
 * {@code src/test/java/org/mybatis/jpetstore/mapper/OrderMapperTest.java}
 * (247 lines, 4 test methods) and adapted for Spring Data JPA with the following
 * transformations:</p>
 * <ul>
 *   <li>MyBatis mapper injection → Spring Data JPA repository injection</li>
 *   <li>JdbcTemplate column verification → native SQL queries via TestEntityManager</li>
 *   <li>Manual orderId assignment → sequence-based auto-generation</li>
 *   <li>java.sql.Timestamp → java.time.LocalDateTime</li>
 *   <li>UPPERCASE HSQLDB column names → snake_case PostgreSQL column names</li>
 * </ul>
 *
 * <p>Uses embedded HSQLDB via {@code @DataJpaTest} with Hibernate DDL generation
 * ({@code create-drop}) for isolated, repeatable testing. Liquibase is disabled
 * since Hibernate generates the schema from JPA entity annotations.</p>
 *
 * @see OrderRepository
 * @see Order
 * @see LineItem
 */
@DataJpaTest
@TestPropertySource(properties = {
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "spring.liquibase.enabled=false",
        "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect"
})
public class OrderRepositoryTest {

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private TestEntityManager entityManager;

    // -------------------------------------------------------------------------
    // Helper method
    // -------------------------------------------------------------------------

    /**
     * Creates a fully-populated {@link Order} entity with all 25+ fields set to
     * the same values used in the monolith's {@code OrderMapperTest} for
     * consistency and traceability.
     *
     * <p>The {@code orderId} is NOT set — it is auto-generated by the PostgreSQL
     * sequence ({@code order_id_seq}) via
     * {@code @GeneratedValue(strategy = SEQUENCE)}.</p>
     *
     * <p>Field values match the monolith's test data:</p>
     * <ul>
     *   <li>username = "j2ee"</li>
     *   <li>orderDate = 2018-12-31T23:59:59</li>
     *   <li>totalPrice = 2000.05 (BigDecimal with string constructor)</li>
     *   <li>status = "P" (matching monolith's initOrder() default)</li>
     *   <li>All ship/bill address, name, payment, and locale fields populated</li>
     * </ul>
     *
     * @return a fully-populated Order entity ready for persistence
     */
    private Order createTestOrder() {
        Order order = new Order();
        order.setUsername("j2ee");
        order.setOrderDate(LocalDateTime.of(2018, 12, 31, 23, 59, 59));
        order.setShipAddress1("Ship Address1");
        order.setShipAddress2("Ship Address2");
        order.setShipCity("Ship City");
        order.setShipState("Ship State");
        order.setShipZip("70001");
        order.setShipCountry("JPN");
        order.setBillAddress1("Bill Address1");
        order.setBillAddress2("Bill Address2");
        order.setBillCity("Bill City");
        order.setBillState("Bill State");
        order.setBillZip("80001");
        order.setBillCountry("USA");
        order.setCourier("Courier");
        order.setTotalPrice(new BigDecimal("2000.05"));
        order.setBillToFirstName("Bill First Name");
        order.setBillToLastName("Bill Last Name");
        order.setShipToFirstName("Ship First Name");
        order.setShipToLastName("Ship Last Name");
        order.setCreditCard("1234 5678 9012 3456");
        order.setExpiryDate("06/2022");
        order.setCardType("Visa");
        order.setLocale("ja");
        order.setStatus("P");
        order.setLineItems(new ArrayList<>());
        return order;
    }

    // -------------------------------------------------------------------------
    // Test 1: findByUsernameOrderByOrderDateDesc
    // Replaces monolith's OrderMapperTest.getOrdersByUsername()
    // -------------------------------------------------------------------------

    /**
     * Verifies that {@link OrderRepository#findByUsernameOrderByOrderDateDesc(String)}
     * returns orders filtered by username and sorted in descending order by
     * order date. This replaces the monolith's
     * {@code OrderMapperTest.getOrdersByUsername()} which tested the
     * {@code getOrdersByUsername} MyBatis mapper method.
     *
     * <p>Validates:</p>
     * <ul>
     *   <li>Filtering: only orders for the specified user are returned</li>
     *   <li>Ordering: newest order first (DESC by orderDate)</li>
     *   <li>All 25+ field values on the first returned order match saved data</li>
     * </ul>
     */
    @Test
    void findByUsernameOrderByOrderDateDesc() {
        // Arrange: Create 2 orders for "j2ee" with different dates
        Order olderOrder = createTestOrder();
        // olderOrder has date 2018-12-31T23:59:59 from createTestOrder()

        Order newerOrder = createTestOrder();
        // Truncate to microseconds since HSQLDB/PostgreSQL TIMESTAMP has microsecond precision,
        // while LocalDateTime.now() returns nanosecond precision, causing mismatch on retrieval
        LocalDateTime newerDate = LocalDateTime.now().truncatedTo(ChronoUnit.MICROS);
        newerOrder.setOrderDate(newerDate);

        // Create 1 order for a different user "ACID" to verify filtering
        Order otherUserOrder = createTestOrder();
        otherUserOrder.setUsername("ACID");

        orderRepository.save(olderOrder);
        orderRepository.save(newerOrder);
        orderRepository.save(otherUserOrder);
        entityManager.flush();
        entityManager.clear();

        // Act
        List<Order> orders = orderRepository.findByUsernameOrderByOrderDateDesc("j2ee");

        // Assert: Result list has exactly 2 orders (ACID user excluded)
        assertThat(orders).hasSize(2);

        // Assert: First order has the newer date (DESC ordering)
        assertThat(orders.get(0).getOrderDate()).isAfter(orders.get(1).getOrderDate());

        // Assert: Verify ALL field values on the first returned order
        Order firstOrder = orders.get(0);
        assertThat(firstOrder.getUsername()).isEqualTo("j2ee");
        assertThat(firstOrder.getOrderDate()).isEqualTo(newerDate);
        assertThat(firstOrder.getTotalPrice()).isEqualByComparingTo(new BigDecimal("2000.05"));
        assertThat(firstOrder.getCardType()).isEqualTo("Visa");
        assertThat(firstOrder.getCreditCard()).isEqualTo("1234 5678 9012 3456");
        assertThat(firstOrder.getExpiryDate()).isEqualTo("06/2022");
        assertThat(firstOrder.getCourier()).isEqualTo("Courier");
        assertThat(firstOrder.getLocale()).isEqualTo("ja");
        assertThat(firstOrder.getStatus()).isEqualTo("P");
        assertThat(firstOrder.getBillAddress1()).isEqualTo("Bill Address1");
        assertThat(firstOrder.getBillAddress2()).isEqualTo("Bill Address2");
        assertThat(firstOrder.getBillCity()).isEqualTo("Bill City");
        assertThat(firstOrder.getBillState()).isEqualTo("Bill State");
        assertThat(firstOrder.getBillZip()).isEqualTo("80001");
        assertThat(firstOrder.getBillCountry()).isEqualTo("USA");
        assertThat(firstOrder.getShipAddress1()).isEqualTo("Ship Address1");
        assertThat(firstOrder.getShipAddress2()).isEqualTo("Ship Address2");
        assertThat(firstOrder.getShipCity()).isEqualTo("Ship City");
        assertThat(firstOrder.getShipState()).isEqualTo("Ship State");
        assertThat(firstOrder.getShipZip()).isEqualTo("70001");
        assertThat(firstOrder.getShipCountry()).isEqualTo("JPN");
        assertThat(firstOrder.getBillToFirstName()).isEqualTo("Bill First Name");
        assertThat(firstOrder.getBillToLastName()).isEqualTo("Bill Last Name");
        assertThat(firstOrder.getShipToFirstName()).isEqualTo("Ship First Name");
        assertThat(firstOrder.getShipToLastName()).isEqualTo("Ship Last Name");

        // Verify second order has the older date
        Order secondOrder = orders.get(1);
        assertThat(secondOrder.getUsername()).isEqualTo("j2ee");
        assertThat(secondOrder.getOrderDate()).isEqualTo(LocalDateTime.of(2018, 12, 31, 23, 59, 59));
    }

    // -------------------------------------------------------------------------
    // Test 2: findById
    // Replaces monolith's OrderMapperTest.getOrder()
    // -------------------------------------------------------------------------

    /**
     * Verifies that {@link OrderRepository#findById(Integer)} returns a fully-
     * populated Order entity with all 25+ fields intact. Uses
     * {@code flush()} + {@code clear()} to evict the L1 cache, forcing a
     * database read. This replaces the monolith's
     * {@code OrderMapperTest.getOrder()} which tested the {@code getOrder}
     * MyBatis mapper method with field-by-field UPPERCASE HSQLDB column
     * assertions.
     */
    @Test
    void findById() {
        // Arrange: Save an order with all fields populated
        Order order = createTestOrder();
        Order savedOrder = orderRepository.save(order);
        int savedId = savedOrder.getOrderId();

        // Flush and clear L1 cache to force DB read
        entityManager.flush();
        entityManager.clear();

        // Act
        Optional<Order> found = orderRepository.findById(savedId);

        // Assert: Optional is present
        assertThat(found).isPresent();
        Order retrieved = found.get();

        // Assert: orderId was generated by sequence (not 0)
        assertThat(retrieved.getOrderId()).isNotEqualTo(0);
        assertThat(retrieved.getOrderId()).isEqualTo(savedId);

        // Assert: All 25+ fields match saved values
        assertThat(retrieved.getUsername()).isEqualTo("j2ee");
        assertThat(retrieved.getOrderDate()).isNotNull();
        assertThat(retrieved.getShipAddress1()).isEqualTo("Ship Address1");
        assertThat(retrieved.getShipAddress2()).isEqualTo("Ship Address2");
        assertThat(retrieved.getShipCity()).isEqualTo("Ship City");
        assertThat(retrieved.getShipState()).isEqualTo("Ship State");
        assertThat(retrieved.getShipZip()).isEqualTo("70001");
        assertThat(retrieved.getShipCountry()).isEqualTo("JPN");
        assertThat(retrieved.getBillAddress1()).isEqualTo("Bill Address1");
        assertThat(retrieved.getBillAddress2()).isEqualTo("Bill Address2");
        assertThat(retrieved.getBillCity()).isEqualTo("Bill City");
        assertThat(retrieved.getBillState()).isEqualTo("Bill State");
        assertThat(retrieved.getBillZip()).isEqualTo("80001");
        assertThat(retrieved.getBillCountry()).isEqualTo("USA");
        assertThat(retrieved.getCourier()).isEqualTo("Courier");
        assertThat(retrieved.getTotalPrice()).isEqualByComparingTo(new BigDecimal("2000.05"));
        assertThat(retrieved.getBillToFirstName()).isEqualTo("Bill First Name");
        assertThat(retrieved.getBillToLastName()).isEqualTo("Bill Last Name");
        assertThat(retrieved.getShipToFirstName()).isEqualTo("Ship First Name");
        assertThat(retrieved.getShipToLastName()).isEqualTo("Ship Last Name");
        assertThat(retrieved.getCreditCard()).isEqualTo("1234 5678 9012 3456");
        assertThat(retrieved.getExpiryDate()).isEqualTo("06/2022");
        assertThat(retrieved.getCardType()).isEqualTo("Visa");
        assertThat(retrieved.getLocale()).isEqualTo("ja");
        assertThat(retrieved.getStatus()).isEqualTo("P");
    }

    // -------------------------------------------------------------------------
    // Test 3: sequenceBasedIdGeneration
    // Validates @GeneratedValue(strategy=SEQUENCE) replaces monolith's
    // non-thread-safe OrderService.getNextId() pattern (AAP Section 0.7.3)
    // -------------------------------------------------------------------------

    /**
     * Verifies that the PostgreSQL sequence-based ID generation works correctly
     * via {@code @GeneratedValue(strategy = GenerationType.SEQUENCE)} with
     * {@code @SequenceGenerator(sequenceName = "order_id_seq")}.
     *
     * <p>This test validates the replacement of the monolith's non-thread-safe
     * {@code OrderService.getNextId()} pattern (read-then-update on the
     * {@code sequence} table) with a database-guaranteed atomic sequence.</p>
     */
    @Test
    void sequenceBasedIdGeneration() {
        // Arrange: Save two consecutive orders
        Order order1 = createTestOrder();
        Order order2 = createTestOrder();

        Order savedOrder1 = orderRepository.save(order1);
        entityManager.flush();

        Order savedOrder2 = orderRepository.save(order2);
        entityManager.flush();

        // Assert: Both have non-zero orderId values (generated, not default int)
        assertThat(savedOrder1.getOrderId()).isNotEqualTo(0);
        assertThat(savedOrder2.getOrderId()).isNotEqualTo(0);

        // Assert: Second orderId > First orderId (ascending sequence)
        assertThat(savedOrder2.getOrderId()).isGreaterThan(savedOrder1.getOrderId());
    }

    // -------------------------------------------------------------------------
    // Test 4: snakeCaseColumnMappingValidation
    // Validates all @Column(name="...") annotations produce correct column names
    // -------------------------------------------------------------------------

    /**
     * Verifies that all {@code @Column(name = "...")} annotations on the
     * {@link Order} entity produce the expected snake_case column names in the
     * database. Uses a native SQL query via {@link TestEntityManager} that
     * explicitly references every column by its expected name — if any column
     * name is incorrect, the query fails with a SQL error.
     *
     * <p>This validates the HSQLDB → PostgreSQL column name mapping documented
     * in the migration column-mapping-manifest:</p>
     * <ul>
     *   <li>{@code orderid → order_id}</li>
     *   <li>{@code shipaddr1 → ship_addr1}</li>
     *   <li>{@code totalprice → total_price}</li>
     *   <li>{@code billtofirstname → bill_to_first_name}</li>
     *   <li>... and all other columns</li>
     * </ul>
     */
    @Test
    void snakeCaseColumnMappingValidation() {
        // Arrange: Save an order with all fields populated
        Order order = createTestOrder();
        Order saved = orderRepository.save(order);
        entityManager.flush();

        // Act: Execute native SQL using exact @Column name annotations.
        // If any column name is wrong, this query throws a SQL exception.
        Object[] row = (Object[]) entityManager.getEntityManager()
                .createNativeQuery(
                        "SELECT order_id, userid, order_date, " +
                                "ship_addr1, ship_addr2, ship_city, ship_state, ship_zip, ship_country, " +
                                "bill_addr1, bill_addr2, bill_city, bill_state, bill_zip, bill_country, " +
                                "courier, total_price, " +
                                "bill_to_first_name, bill_to_last_name, " +
                                "ship_to_first_name, ship_to_last_name, " +
                                "credit_card, expr_date, card_type, locale, status " +
                                "FROM orders WHERE order_id = ?1")
                .setParameter(1, saved.getOrderId())
                .getSingleResult();

        // Assert: Query succeeded (all column names exist) and values match
        assertThat(row).isNotNull();
        assertThat(row).hasSize(26);

        // Spot-check critical column values to verify data integrity
        // row[0] = order_id
        assertThat(((Number) row[0]).intValue()).isEqualTo(saved.getOrderId());
        // row[1] = userid (the @Column name for the 'username' Java field)
        assertThat(row[1]).isEqualTo("j2ee");
        // row[3] = ship_addr1
        assertThat(row[3]).isEqualTo("Ship Address1");
        // row[11] = bill_city
        assertThat(row[11]).isEqualTo("Bill City");
        // row[16] = total_price
        assertThat(new BigDecimal(row[16].toString())).isEqualByComparingTo(new BigDecimal("2000.05"));
        // row[17] = bill_to_first_name
        assertThat(row[17]).isEqualTo("Bill First Name");
        // row[20] = ship_to_last_name
        assertThat(row[20]).isEqualTo("Ship Last Name");
        // row[21] = credit_card
        assertThat(row[21]).isEqualTo("1234 5678 9012 3456");
        // row[22] = expr_date
        assertThat(row[22]).isEqualTo("06/2022");
        // row[23] = card_type
        assertThat(row[23]).isEqualTo("Visa");
        // row[24] = locale
        assertThat(row[24]).isEqualTo("ja");
        // row[25] = status
        assertThat(row[25]).isEqualTo("P");
    }

    // -------------------------------------------------------------------------
    // Test 5: findByUsername_nonExistentUser_returnsEmptyList
    // Edge case: empty result handling
    // -------------------------------------------------------------------------

    /**
     * Verifies that querying for a non-existent username returns an empty list
     * rather than null, ensuring proper handling of missing data.
     */
    @Test
    void findByUsername_nonExistentUser_returnsEmptyList() {
        // Act: Query for a user that has no orders
        List<Order> orders = orderRepository.findByUsernameOrderByOrderDateDesc("nonexistent");

        // Assert: Result is an empty list
        assertThat(orders).isEmpty();
        assertThat(orders.size()).isEqualTo(0);
    }

    // -------------------------------------------------------------------------
    // Test 6: totalPriceBigDecimalPrecision
    // Validates decimal(10,2) precision for monetary fields
    // -------------------------------------------------------------------------

    /**
     * Verifies that the {@code totalPrice} field preserves exact
     * {@link BigDecimal} precision through the JPA persistence cycle. Uses the
     * string constructor {@code new BigDecimal("2000.05")} for exact decimal
     * representation, matching the monolith's {@code OrderMapperTest} pattern.
     *
     * <p>Validates that the PostgreSQL {@code numeric(10,2)} column type
     * (mapped via {@code @Column(precision = 10, scale = 2)}) preserves
     * monetary precision without floating-point rounding errors.</p>
     */
    @Test
    void totalPriceBigDecimalPrecision() {
        // Arrange: Create order with precise BigDecimal totalPrice
        Order order = createTestOrder();
        order.setTotalPrice(new BigDecimal("2000.05"));
        Order saved = orderRepository.save(order);
        entityManager.flush();
        entityManager.clear();

        // Act: Retrieve the order
        Optional<Order> found = orderRepository.findById(saved.getOrderId());

        // Assert: BigDecimal value matches exactly
        assertThat(found).isPresent();
        assertThat(found.get().getTotalPrice()).isEqualByComparingTo(new BigDecimal("2000.05"));

        // Assert: Scale is 2 (matching decimal(10,2) schema)
        assertThat(found.get().getTotalPrice().scale()).isLessThanOrEqualTo(2);
        assertThat(found.get().getTotalPrice().compareTo(new BigDecimal("2000.05"))).isEqualTo(0);
    }

    // -------------------------------------------------------------------------
    // Test 7: save_cascadesLineItems
    // Validates @OneToMany(cascade = CascadeType.ALL) on Order entity
    // -------------------------------------------------------------------------

    /**
     * Verifies that saving an {@link Order} with {@link LineItem} entities in
     * its {@code lineItems} collection correctly cascades the INSERT operations
     * to the {@code lineitem} table via
     * {@code @OneToMany(cascade = CascadeType.ALL)}.
     *
     * <p>Creates an Order with 2 LineItem entities, saves the Order, then
     * retrieves it and verifies both line items are present with correct
     * field values.</p>
     */
    @Test
    void save_cascadesLineItems() {
        // Arrange: Create order and persist to get the generated orderId
        Order order = createTestOrder();
        Order savedOrder = orderRepository.saveAndFlush(order);
        int orderId = savedOrder.getOrderId();
        assertThat(orderId).isNotEqualTo(0);

        // Create 2 LineItem entities with the generated orderId
        LineItem lineItem1 = new LineItem();
        lineItem1.setOrderId(orderId);
        lineItem1.setLineNum(1);
        lineItem1.setItemId("EST-1");
        lineItem1.setQuantity(4);
        lineItem1.setUnitPrice(new BigDecimal("100.00"));

        LineItem lineItem2 = new LineItem();
        lineItem2.setOrderId(orderId);
        lineItem2.setLineNum(2);
        lineItem2.setItemId("EST-2");
        lineItem2.setQuantity(2);
        lineItem2.setUnitPrice(new BigDecimal("50.00"));

        // Add line items to the order's collection
        savedOrder.addLineItem(lineItem1);
        savedOrder.addLineItem(lineItem2);

        // Act: Save order — cascade should persist line items
        orderRepository.saveAndFlush(savedOrder);
        entityManager.clear();

        // Assert: Retrieve the order and verify cascaded line items
        Optional<Order> found = orderRepository.findById(orderId);
        assertThat(found).isPresent();

        Order retrievedOrder = found.get();
        List<LineItem> lineItems = retrievedOrder.getLineItems();
        assertThat(lineItems).hasSize(2);

        // Line items are ordered by lineNum ASC (@OrderBy)
        LineItem retrievedLi1 = lineItems.get(0);
        assertThat(retrievedLi1.getOrderId()).isEqualTo(orderId);
        assertThat(retrievedLi1.getLineNum()).isEqualTo(1);
        assertThat(retrievedLi1.getItemId()).isEqualTo("EST-1");
        assertThat(retrievedLi1.getQuantity()).isEqualTo(4);
        assertThat(retrievedLi1.getUnitPrice()).isEqualByComparingTo(new BigDecimal("100.00"));

        LineItem retrievedLi2 = lineItems.get(1);
        assertThat(retrievedLi2.getOrderId()).isEqualTo(orderId);
        assertThat(retrievedLi2.getLineNum()).isEqualTo(2);
        assertThat(retrievedLi2.getItemId()).isEqualTo("EST-2");
        assertThat(retrievedLi2.getQuantity()).isEqualTo(2);
        assertThat(retrievedLi2.getUnitPrice()).isEqualByComparingTo(new BigDecimal("50.00"));
    }
}
