package com.jpetstore.order.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Data Transfer Object for order responses in the Order Service REST API.
 *
 * <p>Returned by {@code GET /api/orders/{id}} and {@code GET /api/orders?username=} endpoints.
 * Combines order data with associated line item details. Maps from the Order JPA entity
 * and associated LineItem entities.</p>
 *
 * <p>This class mirrors all 27 fields from the monolith's {@code org.mybatis.jpetstore.domain.Order}
 * with the following modernizations:</p>
 * <ul>
 *   <li>{@code orderDate} uses {@link LocalDateTime} instead of {@code java.util.Date}</li>
 *   <li>All monetary fields use {@link BigDecimal} (never double or float)</li>
 *   <li>Line items are represented as embedded {@link LineItemDetail} objects</li>
 *   <li>The {@code status} field supports Saga states: PENDING, CONFIRMED, FAILED</li>
 * </ul>
 *
 * <p>This is a pure data container with no business logic, JPA annotations,
 * or validation annotations (validation belongs on request DTOs, not response DTOs).</p>
 */
public class OrderDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    // ── Order identification ──────────────────────────────────────────────────

    /** Primary order identifier, generated by PostgreSQL sequence. */
    private int orderId;

    /** Username of the account that placed this order. */
    private String username;

    /** Timestamp when the order was created. Uses modern LocalDateTime (replaces java.util.Date). */
    private LocalDateTime orderDate;

    // ── Shipping address fields ───────────────────────────────────────────────

    /** Shipping address line 1. */
    private String shipAddress1;

    /** Shipping address line 2 (nullable). */
    private String shipAddress2;

    /** Shipping city. */
    private String shipCity;

    /** Shipping state/province. */
    private String shipState;

    /** Shipping postal/zip code. */
    private String shipZip;

    /** Shipping country. */
    private String shipCountry;

    // ── Billing address fields ────────────────────────────────────────────────

    /** Billing address line 1. */
    private String billAddress1;

    /** Billing address line 2 (nullable). */
    private String billAddress2;

    /** Billing city. */
    private String billCity;

    /** Billing state/province. */
    private String billState;

    /** Billing postal/zip code. */
    private String billZip;

    /** Billing country. */
    private String billCountry;

    // ── Order details ─────────────────────────────────────────────────────────

    /** Shipping courier (e.g., "UPS"). */
    private String courier;

    /**
     * Total price of the order. Uses BigDecimal for precise monetary arithmetic
     * (never double or float), matching the monolith pattern.
     */
    private BigDecimal totalPrice;

    // ── Name fields ───────────────────────────────────────────────────────────

    /** Billing recipient first name. */
    private String billToFirstName;

    /** Billing recipient last name. */
    private String billToLastName;

    /** Shipping recipient first name. */
    private String shipToFirstName;

    /** Shipping recipient last name. */
    private String shipToLastName;

    // ── Payment fields ────────────────────────────────────────────────────────

    /** Credit card number (e.g., "999 9999 9999 9999"). */
    private String creditCard;

    /** Credit card expiry date as a string (e.g., "12/03"). */
    private String expiryDate;

    /** Credit card type. Values: "Visa", "MasterCard", "American Express". */
    private String cardType;

    // ── Miscellaneous fields ──────────────────────────────────────────────────

    /** Locale code (e.g., "CA"). */
    private String locale;

    /**
     * Order status. Supports Saga states: PENDING, CONFIRMED, FAILED.
     * In the monolith, the initial status is "P".
     */
    private String status;

    /** List of line item details embedded in this order response. */
    private List<LineItemDetail> lineItems;

    // ── No-arg constructor ────────────────────────────────────────────────────

    /**
     * Default no-arg constructor required for JSON deserialization
     * and framework compatibility.
     */
    public OrderDTO() {
        // No-arg constructor for serialization/deserialization
    }

    // ── Getters and Setters ───────────────────────────────────────────────────

    /**
     * Returns the order identifier.
     *
     * @return the order ID
     */
    public int getOrderId() {
        return orderId;
    }

    /**
     * Sets the order identifier.
     *
     * @param orderId the order ID to set
     */
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    /**
     * Returns the username of the account that placed this order.
     *
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username of the account that placed this order.
     *
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Returns the date and time when the order was created.
     *
     * @return the order date as LocalDateTime
     */
    public LocalDateTime getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the date and time when the order was created.
     *
     * @param orderDate the order date to set
     */
    public void setOrderDate(LocalDateTime orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * Returns shipping address line 1.
     *
     * @return the shipping address line 1
     */
    public String getShipAddress1() {
        return shipAddress1;
    }

    /**
     * Sets shipping address line 1.
     *
     * @param shipAddress1 the shipping address line 1 to set
     */
    public void setShipAddress1(String shipAddress1) {
        this.shipAddress1 = shipAddress1;
    }

    /**
     * Returns shipping address line 2.
     *
     * @return the shipping address line 2 (may be null)
     */
    public String getShipAddress2() {
        return shipAddress2;
    }

    /**
     * Sets shipping address line 2.
     *
     * @param shipAddress2 the shipping address line 2 to set
     */
    public void setShipAddress2(String shipAddress2) {
        this.shipAddress2 = shipAddress2;
    }

    /**
     * Returns the shipping city.
     *
     * @return the shipping city
     */
    public String getShipCity() {
        return shipCity;
    }

    /**
     * Sets the shipping city.
     *
     * @param shipCity the shipping city to set
     */
    public void setShipCity(String shipCity) {
        this.shipCity = shipCity;
    }

    /**
     * Returns the shipping state/province.
     *
     * @return the shipping state
     */
    public String getShipState() {
        return shipState;
    }

    /**
     * Sets the shipping state/province.
     *
     * @param shipState the shipping state to set
     */
    public void setShipState(String shipState) {
        this.shipState = shipState;
    }

    /**
     * Returns the shipping postal/zip code.
     *
     * @return the shipping zip code
     */
    public String getShipZip() {
        return shipZip;
    }

    /**
     * Sets the shipping postal/zip code.
     *
     * @param shipZip the shipping zip code to set
     */
    public void setShipZip(String shipZip) {
        this.shipZip = shipZip;
    }

    /**
     * Returns the shipping country.
     *
     * @return the shipping country
     */
    public String getShipCountry() {
        return shipCountry;
    }

    /**
     * Sets the shipping country.
     *
     * @param shipCountry the shipping country to set
     */
    public void setShipCountry(String shipCountry) {
        this.shipCountry = shipCountry;
    }

    /**
     * Returns billing address line 1.
     *
     * @return the billing address line 1
     */
    public String getBillAddress1() {
        return billAddress1;
    }

    /**
     * Sets billing address line 1.
     *
     * @param billAddress1 the billing address line 1 to set
     */
    public void setBillAddress1(String billAddress1) {
        this.billAddress1 = billAddress1;
    }

    /**
     * Returns billing address line 2.
     *
     * @return the billing address line 2 (may be null)
     */
    public String getBillAddress2() {
        return billAddress2;
    }

    /**
     * Sets billing address line 2.
     *
     * @param billAddress2 the billing address line 2 to set
     */
    public void setBillAddress2(String billAddress2) {
        this.billAddress2 = billAddress2;
    }

    /**
     * Returns the billing city.
     *
     * @return the billing city
     */
    public String getBillCity() {
        return billCity;
    }

    /**
     * Sets the billing city.
     *
     * @param billCity the billing city to set
     */
    public void setBillCity(String billCity) {
        this.billCity = billCity;
    }

    /**
     * Returns the billing state/province.
     *
     * @return the billing state
     */
    public String getBillState() {
        return billState;
    }

    /**
     * Sets the billing state/province.
     *
     * @param billState the billing state to set
     */
    public void setBillState(String billState) {
        this.billState = billState;
    }

    /**
     * Returns the billing postal/zip code.
     *
     * @return the billing zip code
     */
    public String getBillZip() {
        return billZip;
    }

    /**
     * Sets the billing postal/zip code.
     *
     * @param billZip the billing zip code to set
     */
    public void setBillZip(String billZip) {
        this.billZip = billZip;
    }

    /**
     * Returns the billing country.
     *
     * @return the billing country
     */
    public String getBillCountry() {
        return billCountry;
    }

    /**
     * Sets the billing country.
     *
     * @param billCountry the billing country to set
     */
    public void setBillCountry(String billCountry) {
        this.billCountry = billCountry;
    }

    /**
     * Returns the shipping courier name.
     *
     * @return the courier (e.g., "UPS")
     */
    public String getCourier() {
        return courier;
    }

    /**
     * Sets the shipping courier name.
     *
     * @param courier the courier to set
     */
    public void setCourier(String courier) {
        this.courier = courier;
    }

    /**
     * Returns the total price of the order as BigDecimal for precise monetary arithmetic.
     *
     * @return the total price (never null for confirmed orders)
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the total price of the order. Must be BigDecimal for monetary precision.
     *
     * @param totalPrice the total price to set
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * Returns the billing recipient's first name.
     *
     * @return the bill-to first name
     */
    public String getBillToFirstName() {
        return billToFirstName;
    }

    /**
     * Sets the billing recipient's first name.
     *
     * @param billToFirstName the bill-to first name to set
     */
    public void setBillToFirstName(String billToFirstName) {
        this.billToFirstName = billToFirstName;
    }

    /**
     * Returns the billing recipient's last name.
     *
     * @return the bill-to last name
     */
    public String getBillToLastName() {
        return billToLastName;
    }

    /**
     * Sets the billing recipient's last name.
     *
     * @param billToLastName the bill-to last name to set
     */
    public void setBillToLastName(String billToLastName) {
        this.billToLastName = billToLastName;
    }

    /**
     * Returns the shipping recipient's first name.
     *
     * @return the ship-to first name
     */
    public String getShipToFirstName() {
        return shipToFirstName;
    }

    /**
     * Sets the shipping recipient's first name.
     *
     * @param shipToFirstName the ship-to first name to set
     */
    public void setShipToFirstName(String shipToFirstName) {
        this.shipToFirstName = shipToFirstName;
    }

    /**
     * Returns the shipping recipient's last name.
     *
     * @return the ship-to last name
     */
    public String getShipToLastName() {
        return shipToLastName;
    }

    /**
     * Sets the shipping recipient's last name.
     *
     * @param shipToLastName the ship-to last name to set
     */
    public void setShipToLastName(String shipToLastName) {
        this.shipToLastName = shipToLastName;
    }

    /**
     * Returns the credit card number.
     *
     * @return the credit card number (e.g., "999 9999 9999 9999")
     */
    public String getCreditCard() {
        return creditCard;
    }

    /**
     * Sets the credit card number.
     *
     * @param creditCard the credit card number to set
     */
    public void setCreditCard(String creditCard) {
        this.creditCard = creditCard;
    }

    /**
     * Returns the credit card expiry date as a string.
     *
     * @return the expiry date (e.g., "12/03")
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the credit card expiry date as a string.
     *
     * @param expiryDate the expiry date to set (e.g., "12/03")
     */
    public void setExpiryDate(String expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * Returns the credit card type.
     *
     * @return the card type (e.g., "Visa", "MasterCard", "American Express")
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * Sets the credit card type.
     *
     * @param cardType the card type to set
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * Returns the locale code.
     *
     * @return the locale (e.g., "CA")
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the locale code.
     *
     * @param locale the locale to set
     */
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * Returns the order status.
     * Supports Saga states: PENDING, CONFIRMED, FAILED.
     * In the monolith, the initial status is "P".
     *
     * @return the order status
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the order status.
     *
     * @param status the status to set (e.g., "PENDING", "CONFIRMED", "FAILED")
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Returns the list of line item details for this order.
     *
     * @return the line items (may be null or empty for orders without items)
     */
    public List<LineItemDetail> getLineItems() {
        return lineItems;
    }

    /**
     * Sets the list of line item details for this order.
     *
     * @param lineItems the line items to set
     */
    public void setLineItems(List<LineItemDetail> lineItems) {
        this.lineItems = lineItems;
    }

    // ── Inner class: LineItemDetail ───────────────────────────────────────────

    /**
     * Embedded line item detail within an order response.
     *
     * <p>Contains the key fields from the monolith's {@code LineItem} domain class:
     * lineNumber, itemId, quantity, unitPrice, and the computed total
     * (unitPrice × quantity). All monetary fields use {@link BigDecimal}.</p>
     *
     * <p>The {@code orderId} field from the monolith's LineItem is intentionally
     * omitted because it is redundant — the line item is always nested within
     * its parent OrderDTO which already carries the orderId.</p>
     */
    public static class LineItemDetail implements Serializable {

        private static final long serialVersionUID = 1L;

        /** Line number within the order (1-based, sequential). */
        private int lineNumber;

        /**
         * Item identifier referencing the catalog item.
         * Cross-service FK to Catalog Service — stored as plain string,
         * not a database constraint (per database-per-service pattern).
         */
        private String itemId;

        /** Quantity of this item ordered. */
        private int quantity;

        /**
         * Unit price of the item at order time.
         * Uses BigDecimal for precise monetary arithmetic (never double or float).
         */
        private BigDecimal unitPrice;

        /**
         * Computed total: unitPrice × quantity.
         * Uses BigDecimal for precise monetary arithmetic (never double or float).
         * Corresponds to the monolith LineItem's calculateTotal() logic.
         */
        private BigDecimal total;

        /**
         * Default no-arg constructor required for JSON deserialization
         * and framework compatibility.
         */
        public LineItemDetail() {
            // No-arg constructor for serialization/deserialization
        }

        /**
         * Returns the line number within the order.
         *
         * @return the line number (1-based)
         */
        public int getLineNumber() {
            return lineNumber;
        }

        /**
         * Sets the line number within the order.
         *
         * @param lineNumber the line number to set
         */
        public void setLineNumber(int lineNumber) {
            this.lineNumber = lineNumber;
        }

        /**
         * Returns the catalog item identifier.
         *
         * @return the item ID (e.g., "EST-1")
         */
        public String getItemId() {
            return itemId;
        }

        /**
         * Sets the catalog item identifier.
         *
         * @param itemId the item ID to set
         */
        public void setItemId(String itemId) {
            this.itemId = itemId;
        }

        /**
         * Returns the quantity ordered.
         *
         * @return the quantity
         */
        public int getQuantity() {
            return quantity;
        }

        /**
         * Sets the quantity ordered.
         *
         * @param quantity the quantity to set
         */
        public void setQuantity(int quantity) {
            this.quantity = quantity;
        }

        /**
         * Returns the unit price as BigDecimal for precise monetary arithmetic.
         *
         * @return the unit price
         */
        public BigDecimal getUnitPrice() {
            return unitPrice;
        }

        /**
         * Sets the unit price. Must be BigDecimal for monetary precision.
         *
         * @param unitPrice the unit price to set
         */
        public void setUnitPrice(BigDecimal unitPrice) {
            this.unitPrice = unitPrice;
        }

        /**
         * Returns the computed total (unitPrice × quantity) as BigDecimal.
         *
         * @return the line item total
         */
        public BigDecimal getTotal() {
            return total;
        }

        /**
         * Sets the computed total. In the service layer, this is typically
         * calculated as {@code unitPrice.multiply(BigDecimal.valueOf(quantity))}.
         *
         * @param total the total to set
         */
        public void setTotal(BigDecimal total) {
            this.total = total;
        }
    }
}
